export const FETCH_FILMS_REQUEST = "FETCH_FILMS_REQUEST";
export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS";
export const FETCH_FILMS_FAILURE = "FETCH_FILMS_FAILURE";
export const SELECT_EPISODE = "SELECT_EPISODE";
export const SET_SORT_VALUE = "SET_SORT_VALUE";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
